config/routes.rb
Rails.application.routes.draw do
  resources :mutual_fund_lists
  resources :mutual_fund_data
  resources :mutual_fund_data
  resources :mutual_fund_data

end

app/models/mutual_fund_datum.rb
class MutualFundDatum < ActiveRecord::Base

end

app/models/mutual_fund_list.rb
class MutualFundList < ActiveRecord::Base

  def get_raw_list_mstar_cats
    url = "http://news.morningstar.com/fund-category-returns/print.aspx"
    response = HTTParty.get url
    dom = Nokogiri::HTML(response.body)
  end

  def push_raw_list_mstar_cats_into_array
    temp_arr = []
    dom = get_raw_list_mstar_cats
    dom.css('td').each do |td|
      if td['colspan'] != '7'
        # puts td.text
        temp_arr << td.text
      end
    end
    # puts temp_arr
    temp_arr
  end

  def save_array_of_mstar_cats_to_database
    temp_arr = push_raw_list_mstar_cats_into_array
    temp_arr = temp_arr.each_slice(7).to_a
    # p temp_arr
    # Comment for git test
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mutual_fund_data_controller.rb
class MutualFundDataController < ApplicationController
  before_action :set_mutual_fund_datum, only: [:show, :edit, :update, :destroy]

  # GET /mutual_fund_data
  # GET /mutual_fund_data.json
  def index
    @mutual_fund_data = MutualFundDatum.all
  end

  # GET /mutual_fund_data/1
  # GET /mutual_fund_data/1.json
  def show
  end

  # GET /mutual_fund_data/new
  def new
    @mutual_fund_datum = MutualFundDatum.new
  end

  # GET /mutual_fund_data/1/edit
  def edit
  end

  # POST /mutual_fund_data
  # POST /mutual_fund_data.json
  def create
    @mutual_fund_datum = MutualFundDatum.new(mutual_fund_datum_params)

    respond_to do |format|
      if @mutual_fund_datum.save
        format.html { redirect_to @mutual_fund_datum, notice: 'Mutual fund datum was successfully created.' }
        format.json { render :show, status: :created, location: @mutual_fund_datum }
      else
        format.html { render :new }
        format.json { render json: @mutual_fund_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutual_fund_data/1
  # PATCH/PUT /mutual_fund_data/1.json
  def update
    respond_to do |format|
      if @mutual_fund_datum.update(mutual_fund_datum_params)
        format.html { redirect_to @mutual_fund_datum, notice: 'Mutual fund datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutual_fund_datum }
      else
        format.html { render :edit }
        format.json { render json: @mutual_fund_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutual_fund_data/1
  # DELETE /mutual_fund_data/1.json
  def destroy
    @mutual_fund_datum.destroy
    respond_to do |format|
      format.html { redirect_to mutual_fund_data_url, notice: 'Mutual fund datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutual_fund_datum
      @mutual_fund_datum = MutualFundDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutual_fund_datum_params
      params.require(:mutual_fund_datum).permit(:raw_yf_date, :raw_mstar_data)
    end
end

app/controllers/mutual_fund_lists_controller.rb
class MutualFundListsController < ApplicationController
  before_action :set_mutual_fund_list, only: [:show, :edit, :update, :destroy]

  # GET /mutual_fund_lists
  # GET /mutual_fund_lists.json
  def index
    @mutual_fund_lists = MutualFundList.all
  end

  # GET /mutual_fund_lists/1
  # GET /mutual_fund_lists/1.json
  def show
  end

  # GET /mutual_fund_lists/new
  def new
    @mutual_fund_list = MutualFundList.new
  end

  # GET /mutual_fund_lists/1/edit
  def edit
  end

  # POST /mutual_fund_lists
  # POST /mutual_fund_lists.json
  def create
    @mutual_fund_list = MutualFundList.new(mutual_fund_list_params)

    respond_to do |format|
      if @mutual_fund_list.save
        format.html { redirect_to @mutual_fund_list, notice: 'Mutual fund list was successfully created.' }
        format.json { render :show, status: :created, location: @mutual_fund_list }
      else
        format.html { render :new }
        format.json { render json: @mutual_fund_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutual_fund_lists/1
  # PATCH/PUT /mutual_fund_lists/1.json
  def update
    respond_to do |format|
      if @mutual_fund_list.update(mutual_fund_list_params)
        format.html { redirect_to @mutual_fund_list, notice: 'Mutual fund list was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutual_fund_list }
      else
        format.html { render :edit }
        format.json { render json: @mutual_fund_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutual_fund_lists/1
  # DELETE /mutual_fund_lists/1.json
  def destroy
    @mutual_fund_list.destroy
    respond_to do |format|
      format.html { redirect_to mutual_fund_lists_url, notice: 'Mutual fund list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutual_fund_list
      @mutual_fund_list = MutualFundList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutual_fund_list_params
      params.require(:mutual_fund_list).permit(:ticker_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mutual_fund_data_helper.rb
module MutualFundDataHelper
end

app/helpers/mutual_fund_lists_helper.rb
module MutualFundListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MutualFundAnalyzer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mutual_fund_data/_form.html.erb
<%= form_for(@mutual_fund_datum) do |f| %>
  <% if @mutual_fund_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mutual_fund_datum.errors.count, "error") %> prohibited this mutual_fund_datum from being saved:</h2>

      <ul>
      <% @mutual_fund_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :raw_yf_date %><br>
    <%= f.text_field :raw_yf_date %>
  </div>
  <div class="field">
    <%= f.label :raw_mstar_data %><br>
    <%= f.text_field :raw_mstar_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mutual_fund_data/edit.html.erb
<h1>Editing Mutual Fund Datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @mutual_fund_datum %> |
<%= link_to 'Back', mutual_fund_data_path %>

app/views/mutual_fund_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mutual Fund Data</h1>

<table>
  <thead>
    <tr>
      <th>Raw yf date</th>
      <th>Raw mstar data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mutual_fund_data.each do |mutual_fund_datum| %>
      <tr>
        <td><%= mutual_fund_datum.raw_yf_date %></td>
        <td><%= mutual_fund_datum.raw_mstar_data %></td>
        <td><%= link_to 'Show', mutual_fund_datum %></td>
        <td><%= link_to 'Edit', edit_mutual_fund_datum_path(mutual_fund_datum) %></td>
        <td><%= link_to 'Destroy', mutual_fund_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mutual fund datum', new_mutual_fund_datum_path %>

app/views/mutual_fund_data/new.html.erb
<h1>New Mutual Fund Datum</h1>

<%= render 'form' %>

<%= link_to 'Back', mutual_fund_data_path %>

app/views/mutual_fund_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Raw yf date:</strong>
  <%= @mutual_fund_datum.raw_yf_date %>
</p>

<p>
  <strong>Raw mstar data:</strong>
  <%= @mutual_fund_datum.raw_mstar_data %>
</p>

<%= link_to 'Edit', edit_mutual_fund_datum_path(@mutual_fund_datum) %> |
<%= link_to 'Back', mutual_fund_data_path %>

app/views/mutual_fund_lists/_form.html.erb
<%= form_for(@mutual_fund_list) do |f| %>
  <% if @mutual_fund_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mutual_fund_list.errors.count, "error") %> prohibited this mutual_fund_list from being saved:</h2>

      <ul>
      <% @mutual_fund_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker_list %><br>
    <%= f.text_field :ticker_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mutual_fund_lists/edit.html.erb
<h1>Editing Mutual Fund List</h1>

<%= render 'form' %>

<%= link_to 'Show', @mutual_fund_list %> |
<%= link_to 'Back', mutual_fund_lists_path %>

app/views/mutual_fund_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mutual Fund Lists</h1>

<table>
  <thead>
    <tr>
      <th>Ticker list</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mutual_fund_lists.each do |mutual_fund_list| %>
      <tr>
        <td><%= mutual_fund_list.ticker_list %></td>
        <td><%= link_to 'Show', mutual_fund_list %></td>
        <td><%= link_to 'Edit', edit_mutual_fund_list_path(mutual_fund_list) %></td>
        <td><%= link_to 'Destroy', mutual_fund_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mutual fund list', new_mutual_fund_list_path %>

app/views/mutual_fund_lists/new.html.erb
<h1>New Mutual Fund List</h1>

<%= render 'form' %>

<%= link_to 'Back', mutual_fund_lists_path %>

app/views/mutual_fund_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker list:</strong>
  <%= @mutual_fund_list.ticker_list %>
</p>

<%= link_to 'Edit', edit_mutual_fund_list_path(@mutual_fund_list) %> |
<%= link_to 'Back', mutual_fund_lists_path %>